In [1]:
import numpy as np

array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [2]:
#Dividindo array 2

arrays_divididos = np.split(array, 3) #A função 'split' recebe o array e um valor(pelo qual o array vai ser repartido) para ser excultado 
arrays_divididos

#i1 = index e i2 = é igual ao valor do index
for i1, i2 in enumerate(arrays_divididos): #Enumerate é usando quando se quer criar uma index
  print('Parte ',i1, ' ->  ', i2)

Parte  0  ->   [1 2]
Parte  1  ->   [3 4]
Parte  2  ->   [5 6]


In [3]:
#Array 1D com temperaturas diárias ao longo do mês (30 dias)

#Criando array de 1D
temperatura = np.array([50,45,44,23,44,22,13,43,15,21,45,33,43,44,33,55,30,33,50,45,44,23,44,21,56,21,22,21])
print('\n',temperatura.shape)

#Quebrando o array em 4 subarrys
tempSemanal = np.split(temperatura, 4)
print('\n', tempSemanal, '\n')

#Printando arrays por  semana
for i, valor in enumerate(tempSemanal):
  print(f'Semana {i} -> {valor}')

#realizando a média do array com axis = 1 para média da linha
media = np.around(np.mean(tempSemanal, axis = 1), 2)
print(media)

#adicionando uma coluna(média) a temperatura semanda
df = np.column_stack((tempSemanal, media)) #sempre usar "()" quando for usar algum join(column_stack, vstack, hstack, concatenate)
print(df)

#Realizando print semana/média temperatura
for i, valor in enumerate(media):
  print(f'Semana {i+1} -> Média = {valor}')


 (28,)

 [array([50, 45, 44, 23, 44, 22, 13]), array([43, 15, 21, 45, 33, 43, 44]), array([33, 55, 30, 33, 50, 45, 44]), array([23, 44, 21, 56, 21, 22, 21])] 

Semana 0 -> [50 45 44 23 44 22 13]
Semana 1 -> [43 15 21 45 33 43 44]
Semana 2 -> [33 55 30 33 50 45 44]
Semana 3 -> [23 44 21 56 21 22 21]
[34.43 34.86 41.43 29.71]
[[50.   45.   44.   23.   44.   22.   13.   34.43]
 [43.   15.   21.   45.   33.   43.   44.   34.86]
 [33.   55.   30.   33.   50.   45.   44.   41.43]
 [23.   44.   21.   56.   21.   22.   21.   29.71]]
Semana 1 -> Média = 34.43
Semana 2 -> Média = 34.86
Semana 3 -> Média = 41.43
Semana 4 -> Média = 29.71


In [4]:
#Divagando

temperatura = np.array([50,45,44,23,44,22,13,43,15,21,45,33,43,44,33,55,30,33,50,45,44,23,44,21,56,21,22,21])
print('\n',temperatura.shape)

tempSemanal = np.split(temperatura, 4)
print('\n', tempSemanal, '\n')

for i, valor in enumerate(tempSemanal):
  print(f'semana {i+1} -> {valor}')

arrayconcet = np.vstack(tempSemanal)

print(arrayconcet)

cabecalho = np.array([["V1", "V2", "V3", "V4", "V5", "V6", "V7"]])
print(cabecalho)

df = np.vstack((cabecalho, arrayconcet)) 
print(df)


 (28,)

 [array([50, 45, 44, 23, 44, 22, 13]), array([43, 15, 21, 45, 33, 43, 44]), array([33, 55, 30, 33, 50, 45, 44]), array([23, 44, 21, 56, 21, 22, 21])] 

semana 1 -> [50 45 44 23 44 22 13]
semana 2 -> [43 15 21 45 33 43 44]
semana 3 -> [33 55 30 33 50 45 44]
semana 4 -> [23 44 21 56 21 22 21]
[[50 45 44 23 44 22 13]
 [43 15 21 45 33 43 44]
 [33 55 30 33 50 45 44]
 [23 44 21 56 21 22 21]]
[['V1' 'V2' 'V3' 'V4' 'V5' 'V6' 'V7']]
[['V1' 'V2' 'V3' 'V4' 'V5' 'V6' 'V7']
 ['50' '45' '44' '23' '44' '22' '13']
 ['43' '15' '21' '45' '33' '43' '44']
 ['33' '55' '30' '33' '50' '45' '44']
 ['23' '44' '21' '56' '21' '22' '21']]
