In [6]:
import numpy as np

In [8]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [9]:
#Função interação do array sum(soma) para arrays
interacao = sum(array)
interacao

np.int64(15)

In [10]:
#Função soma posição a posição do array
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [12]:
#Função de subtração!
 
subtracao = np.subtract(array, 2)
print(subtracao)

[-1  0  1  2  3]


In [13]:
#Função de Multiplicação!
 
produto = np.multiply(array, 2)
print(produto)


[ 2  4  6  8 10]


In [14]:
#função de divisão
 
divisao = np.divide(array, 2)
print(divisao)

[0.5 1.  1.5 2.  2.5]


In [16]:
#funções trigonometricas
 
#Seno
seno = np.sin(array)
print(seno)

#Cosseno
cosseno = np.cos(array)
print(cosseno)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [17]:
#Média
media = np.mean(array)
print(media)
 
#Desvio Padrão
desvioPadrao = np.std(array)
print(desvioPadrao)


3.0
1.4142135623730951


In [ ]:
#Funções de comparação ou funções de Mascara
 
comparacaoMaior3 = array > 3
print(comparacaoMaior3)

[False False False  True  True]


In [19]:
 
#Combinado Funçãoes
 
#Raiz quadrada de cada posição + potênciação de 2 de cada posição
resultado = np.sqrt(array) + np.power(array, 2)
print(resultado)


[ 2.          5.41421356 10.73205081 18.         27.23606798]


In [ ]:
#Funções Expeonenciais
 
#As funções esponeciais usam a a constante de Euler = 2,71828182...
exp = np.exp(array)
print(exp)


In [20]:
#Funções de Logaritimo
 
log = np.log(array)
print(log)


[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [21]:
#Funções de arredondamento
 
arrendondado = np.around(array)
print(arrendondado)

[1 2 3 4 5]


In [22]:
#Função de potência
 
pot = np.power(array, 2)
print(pot)


[ 1  4  9 16 25]
