In [2]:

import numpy as np

array = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(array.shape)
array.ndim

(3, 3)


2

In [3]:
#1-Interação simples usando loop for

for i in array:
  print(i)


for i in array:
  for j in array:
    print (j, end=' ') #Constrent (end = ' ') deixa tudo na mesma linha

[1 2 3]
[4 5 6]
[7 8 9]
[1 2 3] [4 5 6] [7 8 9] [1 2 3] [4 5 6] [7 8 9] [1 2 3] [4 5 6] [7 8 9] 

In [4]:
#2-usando o np.nditer para uma interação mais eficiênte

for valor in np.nditer(array):
  print(valor, end=' ')

1 2 3 4 5 6 7 8 9 

In [5]:
#3-Interação com condição

for valor in np.nditer(array):
  if valor > 5:
    print(valor, end= ' ')

6 7 8 9 

In [6]:
#4-Interação com índiceis

for i in range(array.shape[0]): #Usa-se o .shape para especificar a posição que você quer acessar no array
   for j in range(array.shape[0]):
    print(f'linha {i} coluna {j} é {array[i, j]}')

linha 0 coluna 0 é 1
linha 0 coluna 1 é 2
linha 0 coluna 2 é 3
linha 1 coluna 0 é 4
linha 1 coluna 1 é 5
linha 1 coluna 2 é 6
linha 2 coluna 0 é 7
linha 2 coluna 1 é 8
linha 2 coluna 2 é 9


In [7]:
#Exercícios de interação

#Iterar sobre matriz por linhas
#Tarefa: imprimir cada linha separadamente.

import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
soma = 0

for i in range(array.shape[0]):
  for j in range(array.shape[0]):
    soma += array[i, j]
    print(f'Posição índice {i} linha {j} = {array[i, j]}')
print(f'\nTotal: {soma}')

Posição índice 0 linha 0 = 1
Posição índice 0 linha 1 = 2
Posição índice 0 linha 2 = 3
Posição índice 1 linha 0 = 4
Posição índice 1 linha 1 = 5
Posição índice 1 linha 2 = 6
Posição índice 2 linha 0 = 7
Posição índice 2 linha 1 = 8
Posição índice 2 linha 2 = 9

Total: 45


In [8]:
#Exercícios de interação

#Iterar sobre todos os elementos com np.nditer

# Tarefa:

# Percorrer elemento por elemento com nditer, mas:

# imprimir o valor
# imprimir o tipo (dtype) de cada elemento
# criar um novo array contendo cada elemento multiplicado por
newArray = []

for valor in np.nditer(array):
  newArray.append(valor)
  print(valor, valor.dtype) #O dtype serve para especificar o type "dtype ='Int32" e verificar o tipo de dado 'array.dtype'

newArray =  np.array([newArray])
newArray = np.multiply(newArray, 2)
newArray = newArray.reshape(3,3)

print('\n', newArray.shape)
print('\n', array.dtype)
print('\n', newArray)

1 int64
2 int64
3 int64
4 int64
5 int64
6 int64
7 int64
8 int64
9 int64

 (3, 3)

 int64

 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
